global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.qq.com:25'
  smtp_from: '591592159@qq.com'
  smtp_auth_username: '591592159@qq.com'
  smtp_auth_password: ''
  smtp_require_tls: false

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 10s
  receiver: 'zs'
  routes:
    - match:
        level: error
      receiver: 'purelight1'
    - match:
        level: info
      receiver: 'zs'

receivers:
  - name: 'purelight1'
    email_configs:
      - to: 'purelightme@gmail.com'
        headers: { Subject: "Prometheus 告警邮件" }
  - name: 'zs'
    email_configs:
      - to: 'purelightme@gmail.com'
        headers: { Subject: "Prometheus 告警了" }

templates:
  - "/templates/*"
